### ISSUE TITLE
dateStart is null

### ISSUE THREAD

**Issue by racinmat** [h4kuna/fio#13]
When I call $this->fioRead->lastDownload(); it ends with fatal error. It is because in json returned from api, dateStart is null, and in method createFromFormat in vendor\h4kuna\fio\src\Utils\String.php:55 is raises fatal error just because of this null value.

**Comment by h4kuna** [comment]
Could you create pull request? Or I will fix it next week.

**Comment by racinmat** [comment]
pull request created

**Comment by h4kuna** [comment]
Do you know why tests are faild?

**Comment by racinmat** [comment]
in failed in php 5.3 due to object notation. Fixed in new PR.
