### ISSUE TITLE
CURLIOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by driici** [h4kuna/fio#27]
Hi, for development I need to temporarily disable SSL verification on my local server. This can be done by settion CURL flag CURLIOPT_SSL_VERIFYPEER, However Guzzle does it as following: http://guzzle.readthedocs.io/en/stable/request-options.html#verify

But by your method Queue::setDownloadOptions it cannot be done due to thrown exception.

**Comment by h4kuna** [comment]
Could you try master? Here is a fix  352b4343

**Comment by driici** [comment]
Yeah, thats it. 
Thanks.

**Comment by h4kuna** [comment]
Released new version 1.3.3
