### ISSUE TITLE
Nedostupnost

### ISSUE THREAD

**Issue by czPechy** [h4kuna/fio#28]
Jelikož jsem hodně časově out, tak nemám čas to nějak pěkně napsat a poslat na pull, ale kdyby se někomu chtělo... Dnes nám asi 15 minut Fio vracela, že je služba nedostupná, bohužel to vrací v XML, ale movements očekává Json, takže to padá na Malformed Json.

Super... Teď jsem si všiml, že mám ještě nějakou starší verzi fia .. snad jen pár let :D ... Takže ani nejsem narychlo schopen říct, jestli to je aktuální , ale ve Files/Json se vyjímka neodchytává ani zde, tak si myslím, že bude.

Konkrétně přijde

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.fio.cz/schema/response.xsd">
	<result> 
		<errorCode>15</errorCode>
		<status>error</status>
		<message>Služba je momentálně nedostupná</message>
	</result>
</response>`

Já si hodil narychlo jen Json::decode do try {} a při chybě to hodím do XMLResponse a vypíšu chybu.

**Comment by h4kuna** [comment]
Odhaduji že to bude chyba na straně API banky. Jak by měla tato knihovna reagovat? Pokud exception převedu na nějakou jinou a vyhodím aby dávala vetší smysl tak to je asi jediný co můžu udělat.

**Comment by czPechy** [comment]
Samozřejmě, že je. 
Nadruhou stranu, buďme rádi, že nám to dají vědět alespoň ve formě XML, než aby při vypnutí služby padaly dotazy na timeout.
Právě by to chtělo nějakou smyslnější chybu, než že je rozsypanej JSON :-)
Já to klidně udělám, jen nevím, kdy se k tomu dostanu. Jestli to stihnu třeba do půl roku 🤔

**Comment by h4kuna** [comment]
Ok, nechám úkol otevřený. Já na to taky budu myslet myslím že to stihnu rychleji jak do půl roka :)

**Comment by czPechy** [comment]
Jelikož dnes od rána má Fio pořád výpadky, tak jsem se na to teda mrkl.
Vyřešil jsem to zatím tak nějak "narychlo" zde: https://github.com/czPechy/fio/commit/90335ad7c84a5c32b8d7c7297ec01703d7cd139b

Podíváš se na to, jestli to tak je přijatelný? Nevím, jestli se někde používá XML, protože používáme knihovnu jen na movements.

**Comment by czPechy** [comment]
Tak už koukám, že tím jsem rozbil upload. :(

**Comment by czPechy** [comment]
Tak nakonec upraveno s kontrolou errorCode, kdyžtak jak bude čas, tak si to projdi, pouprav co je potřeba, nijak moc jsem se nerozhlížel :(
https://github.com/czPechy/fio/commit/021e0bb1a8b678bc649dd68264e7939460f77bb9

**Comment by h4kuna** [comment]
Je to v mastru, dej mi vědět jestli je to ok?

**Comment by czPechy** [comment]
Super, hodil jsem to do produkce, vypadá to dobře, uvidíme u výpadku :-)
Díky moc 👍

**Comment by h4kuna** [comment]
Obalil jsis to do bloku try catch? na tu novou exception?

**Comment by czPechy** [comment]
Máme to v cron tascích, kde se chytá každá exception a pak nás spamuje, dokud to neopravíme.
Takže jsem to nejdřív nechal bez toho, ať vidím, zda to funguje.
Jakmile mě to zaspamuje, tak budu vědět, že to frčí a obalím.

**Comment by czPechy** [comment]
btw. chybí ti tu beer donate 🎉

**Comment by h4kuna** [comment]
:) dělám to ve jménu míru na světě

**Comment by czPechy** [comment]
Dnes spíše dotaz.
Fio právě chvilku vracelo 500, což padlo ihned v Guzzle.

GuzzleHttp\Exception\ServerException #500

Nebylo by fajn to také zakomponovat do ServiceUnavailableException ?

**Comment by h4kuna** [comment]
určitě ano

**Comment by czPechy** [comment]
Mám se na to mrknout ?

**Comment by h4kuna** [comment]
ano prosím

**Comment by czPechy** [comment]
Přidal jsem do PR. 
Ještě jsem chtěl udělat nějaký testy, ale tak nějak moc nevím, jak rychle bych byl schopen rozjet nějakej mockup, takže nakonec je tam test jen na response->isOk 😢

**Comment by czPechy** [comment]
Tak tam byla chybka, také opraveno v PR.

**Comment by h4kuna** [comment]
Poslední verze v mastru už řeší nedostupnost, nicméně ještě není stable.
