### ISSUE TITLE
Queue::createXmlResponse calls getBody on Stream

### ISSUE THREAD

**Issue by Tetragramat** [h4kuna/fio#31]
Sending payments is now broken.

```
In Queue.php line 187:
                                                                                            
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                              
  Attempted to call an undefined method named "getBody" of class "GuzzleHttp\Psr7\Stream".  
```
Method Queue::createXmlResponse contains invalid typehint. 
Instead ResponseInterface|GuzzleHttp\Psr7\Stream should be ResponseInterface.

On the line src/Request/Queue.php:91 is Queue::createXmlResponse called with wrong argument.

It was broken by [lastest commit](https://github.com/h4kuna/fio/commit/384d9c1383df51eaf809204180507cb9c881d321)

**Comment by h4kuna** [comment]
Thank you for report, could you try this [fix](/h4kuna/fio/commit/589fec46050695f06a1198ef1100e8ab5bd665b3) in this branch [fix-invalid-typehint](/h4kuna/fio/tree/fix-invalid-typehint)?

**Comment by Tetragramat** [comment]
I'm unable to test it.
There should be unit tests for that.

**Comment by h4kuna** [comment]
You have right. In this moment for this use case, tests does not exists. Could you send PR?

**Comment by h4kuna** [comment]
Merge to master and releas new version
