### ISSUE TITLE
Kontrola čísla účtu

### ISSUE THREAD

**Issue by maxiorel** [h4kuna/fio#32]
Regulár pro kontrolu čísla účtu má podle mě chybu, takže účet 123456789/0123 přes něj neprojde.

Místo '~^(?P<account>[a-z0-9]{1,34})(?P<code>/[a-z0-9]{11})?$~i'
je podle mě potřeba toto: '~^(?P<account>[a-z0-9]{1,34})(?P<code>/[a-z0-9]{1,11})?$~i'

**Comment by h4kuna** [comment]
Prosím tě a vzal jsi v potaz ze jsou tam dvě metody? Pro kontrolu mezinárodního účtu a vnitrostátního. Ten co píšeš je i v [testech](src/tests/src/Account/BankTest.php#L24)a

**Comment by maxiorel** [comment]
tak asi mi něco uniká.
$fioPay->createNational(100, '123456789/0600');
mi na tom havarovalo.

**Comment by h4kuna** [comment]
No tak na tom už se dá stavět. Tady je [chyba](/h4kuna/fio/blob/master/src/FioPay.php#L63), opravím.

**Comment by h4kuna** [comment]
Je to opravené ve verzi v2.0.1
