### ISSUE TITLE
Jak získat XML file?

### ISSUE THREAD

**Issue by landsman** [h4kuna/fio#33]
Vidím, že mohu poslat hromadný import rovnou na fio api, ale rád bych prvně dostal xml file.
Asi bude stačit zpřístupnit `$this->xmlFile` ve `FioPay` nebo tě napadá bezpečnější způsob?

**Comment by h4kuna** [comment]
K tomu aby ti zůstával xml soubor v tempu a mohl jsis ho prohlídnout slouží [FioPay::enableLog()](/h4kuna/fio/blob/master/src/FioPay.php#L40). Zformátovat si ho můžeš v IDE.

```php
$log = $fioPay->enableLog();
$fioPay->send();
var_dump($log->getContent());
```

**Comment by landsman** [comment]
No já to právě na FIO nechci posílat, bez manuální kontroly.
Pak se to z něj blbě maže, nemají tam hromadné zrušení dávky.

**Comment by h4kuna** [comment]
No dobře tak ten log bude potřeba vylepšit aby to zapsalo do souboru a neposílal na api, to je legitimní požadavek. Respektive udělat nějaký dry režim.

**Comment by h4kuna** [comment]
Pokračování #36

**Comment by h4kuna** [comment]
Můžeš vyzkoušet větev logging
Myslím že to natáhneš pomocí composeru takto
`composer requre h4kuna/fio:dev-logging`
