### ISSUE TITLE
Nepovinný BIC

### ISSUE THREAD

**Issue by Simtrix** [h4kuna/fio#37]
Je možné u euro plateb udělat BIC nepovinný? Třeba, aby měl defaulní hodnotu NULL? Když nebude NULL, kontrolovat na délku 11 znaků jinak nechat být?

**Comment by h4kuna** [comment]
Je dost možný že BIC přestal být povinný, je možné toto změnit. Zítra na to kouknu a napíšu.

**Comment by h4kuna** [comment]
vydána verze 2.0.2
