### ISSUE TITLE
Chyba v iterovaném TransactionList

### ISSUE THREAD

**Issue by pupitooo** [h4kuna/fio#42]
https://github.com/h4kuna/fio/blob/5b9919b8feddd54e44b16e089aa3777a85ff0ede/src/Response/Read/TransactionList.php#L49

Nepodařilo sem mi identifikovat proč, ale v jednom případě se mi Transactin list ve foreach zacyklí a začne házet `false` výsledky pro větší počet dat, než v něm je. Tenhle fix pomohl. Mám za to, že to přetypování na int tam je špatně, protože to `null` převede na `0` a pak to vrací vždy že další hodnota existuje.

```php
$key = key($this->transactions);
if ($key === null) {
	return null;
}
return (int) $key;
```

**Comment by h4kuna** [comment]
Opraveno 1161ba77ab2d7d0f89798368d89482149846b811
