### ISSUE TITLE
Variabilní symbol by měl být interpretován jako string, nikolik jako integer

### ISSUE THREAD

**Issue by lucasow** [h4kuna/fio#49]
$national->setVariableSymbol($vs); očekává string parametr. 

Už se nám však stalo, že VS řetězec u dodavatele začíná 0. V případě, že bychom s proměnou nakládali jako s číslem, úvodní 0 by se z řetězce vypustila a došlo by tak k platbě se špatným VS. 

I ISDOC podle dokumentace nakládá s VS jako se string: https://www.mvcr.cz/isdoc/soubor/isdoc-schema-6-0-1-20140526-zip.aspx

**Comment by h4kuna** [comment]
Ok, dokážeš udělat PR?

**Comment by h4kuna** [comment]
Oprava je v mastru bb8f6fed5077492f05ae268eef6fdc4d699f9459. Můžeš to testnout?

**Comment by h4kuna** [comment]
V composeru v `require` máš
```
"h4kuna/fio": "^3.0"
```
tak to uprav na `dev-master`
```
"h4kuna/fio": "dev-master"
```

a potom `composer update h4kuna/fio`

**Comment by h4kuna** [comment]
Released [v3.0.2](/h4kuna/fio/releases/tag/v3.0.2)
