### ISSUE TITLE
Změna URL adresy

### ISSUE THREAD

**Issue by vzikmund** [h4kuna/fio#56]
Ahoj, 
FIO plánuje změnu URL pro API. Ze současné `https://www.fio.cz/ib_api/` přechází na `https://fioapi.fio.cz/v1/` viz [https://www.fio.cz/bankovni-sluzby/api-bankovnictvi](https://www.fio.cz/bankovni-sluzby/api-bankovnictvi).

Čas na změnu je do 30.11.2024. Kouknul bys na to? 🙏 

Díky 🫡

**Comment by h4kuna** [comment]
Od včera je nová verze 3.0.8 kde je nová url

**Comment by vzikmund** [comment]
@h4kuna Šlo by to i do verze 2.x.x, která podporuje i php7.4? Balíček mám na starším projektu, kde se nám nepodařilo ještě úplně dohnat technologický dluh :)

**Comment by h4kuna** [comment]
Udělej PR a sloučím ti to.

**Comment by vzikmund** [comment]
Ty už to na branchi `v2.x` máš https://github.com/h4kuna/fio/blob/6abb98e6fa7131188b8a5f1c203db227730b70e4/src/Fio.php#L14

 ale v tagu `v2.0.7` 
https://github.com/h4kuna/fio/blob/201af966e46f7fa382206e76066504bf13b5a0d9/src/Fio.php#L14 to není 🤔

**Comment by h4kuna** [comment]
koukal jsem na to, upravoval jsem k tomu testy, byl jsi rychlejší než jsem vydal `v2.0.8`

**Comment by vzikmund** [comment]
Aha :D Děkuji 🚀
