### ISSUE TITLE
Import payments is missing content-type header

### ISSUE THREAD

**Issue by Tetragramat** [h4kuna/fio#60]
Request `POST "https://fioapi.fio.cz/v1/rest/import/"` is being send without header `Content-Type: multipart/form-data`.

That means payment imports don't work and end with `400 Bad Request` and html content containing `Required request parameter 'token' for method parameter type String is not present`.

**Comment by h4kuna** [comment]
Could you show me how do you build FioPay and use it? Because token is added to [request here](https://github.com/h4kuna/fio/blob/master/src/FioPay.php#L134).

**Comment by h4kuna** [comment]
I fixed. If I use GuzzleHttp\Psr7\MultipartStream, the guzzle automaticaly set header multipart with right boundary. If you use symfony client, you found the bug. Could you try master. I tested too :)

**Comment by h4kuna** [comment]
fixed v3.0.11
